version: "3.7"
services:
  mongodb:
    image : mongo
    container_name: mongodb_mentoring
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./mongodb/database:/data/db
    ports:
      - 27017:27017
    restart: unless-stopped
