version: '3.7'
services:
  postgres:
    image: postgres:12
    container_name: postgres_mentoring
    environment: 
      - POSTGRES_DB=mentoring
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - ./postgres/database:/data/db
    ports:
      - 5432:5432
    restart: unless-stopped
